#эмулятор сообщений на CAN-шине в соотвествии со стандартом Bosch Common Rail SAE J1939:
#Common Rail — это технология впрыска топлива,
#используемая в современных дизельных двигателях.



#структура ID (расширенный идентификатор пакета) стр.17
#|3bit|1bit|1bit|8bit|8bit|8bit|
#|P	  |EDP |DP	|   PGN    |SA

#P - приоритет сообщения
#EDP и DP - обычно 0х0 и 0х0
#PGN - ID одного из модулей устройства
#SA - ID самого устройства

#таблица ID устройств стр.8
#|  SA  | Устройство |
#| 0x00 | Блок управления двигателем (ECU) |
#| 0x03 | Блок управления силовой установкой |
#| 0x0B | Электронная тормозная система (EBS) |
#| 0x0F | Тормоз двигателя |
#| 0x10 | Тормоз силовой установки |
#| 0x17 | Instrument - Прибор |
#| 0x21 | Кузов автомобиля |
#| 0x24 | Блок отбора мощности (PTO) |
#| 0x27 | Интеллектуальный центр автомобиля |
#| 0x29 | Тормоз выхлопных газов |
#| 0x2B | Бортовая диагностическая система |
#| 0x3D | Блок управления системой последующей обработки |
#| 0xEE | Спидометр |
#| 0xF9 | Инструмент диагностики неисправностей – инструмент послепродажного обслуживания |

#Общий список полученных сообщений (таблица PGN) стр.19
#DM13 (Diagnostic Message 13):
#PGN: 0xDF00 (57088), Priority: 6, Length: 8 bytes, Sending Cycle: 5000 ms.
#Этот пакет используется для диагностики сети, совместимости и передачи различных диагностических команд и данных состояния сети.
#EBC1 (Electronic Brake Controller 1):
#PGN: 0xF001 (61441), Priority: 6, Length: 8 bytes, Sending Cycle: 100 ms.
#Сообщение содержит данные, связанные с электронной системой управления тормозами, такие как активность ASR (Anti-Slip Regulation) и ABS (Antilock Braking System).
#ETC1 (Electronic Transmission Controller 1):
#PGN: 0xF002 (61442), Priority: 3, Length: 8 bytes, Sending Cycle: 10 ms.
#Дает информацию о состоянии трансмиссии, таких как скорость отводного вала трансмиссии и условия блокировки преобразователя крутящего момента.
#ETC2 (Electronic Transmission Controller 2):
#PGN: 0xF005 (61445), Priority: 6, Length: 8 bytes, Sending Cycle: 100 ms.
#Содержит данные о текущем и выбранном передаточных числах, а также реальном коэффициенте передачи.
#RQST (Request):
#PGN: 0xEA00 (59904), Priority: 6, Length: 3 bytes, Sending Cycle: on demand.
#Инструкция в этом сообщении запрашивает определенные данные от другого ECU, по запросу.
#CCVS (Cruise Control/Vehicle Speed):
#PGN: 0xFEF1 (65265), Priority: 6, Length: 8 bytes, Sending Cycle: 100 ms.
#Назначение: Передает информацию о круиз-контроле и скорости транспортного средства, такие как скорость, активность круиз-контроля и состояние различных переключателей.
#TCO1 (Transmission Control 1):
#PGN: 0xFE6C (65132), Priority: 3, Length: 8 bytes, Sending Cycle: 50 ms.
#Назначение: Включает данные о скорости транспортного средства на основе скорости колес, а также информацию о трансмиссии и состоянии отдельных узлов.
#.......................

#Общий список отправленных сообщений стр.19

#ACK - Подтверждение (Acknowledgment)
#PGN: 0xE800
#Период: On request
#Длина: 8 байт
#ID: 0x18E8FF00
#AMB - Барометрическое давление (Barometric Pressure)
#PGN: 0xFEF5
#Период: 1000 мс
#Длина: 8 байт
#ID: 0x18FEF500
#CCVS - Скорость автомобиля при круиз-контроле (Cruise Control Vehicle Speed)
#PGN: 0xFEF1
#Период: 100 мс
#Длина: 8 байт
#ID: 0x18FEF100
#DM1 - Диагностическое сообщение 1 (Diagnostic Message 1)
#PGN: 0xFECA
#Период: 1000 мс
#Длина: Переменная
#ID: 0x18FECA00
#DM2 - Диагностическое сообщение 2 (Diagnostic Message 2)
#PGN: 0xFECB
#Период: On request
#Длина: Переменная
#ID: 0x18FECB00
#EEC1 - Электронный контроллер двигателя 1 (Electronic Engine Controller 1)
#PGN: 0xF004
#Период: 10 мс
#Длина: 8 байт
#ID: 0x0CF00400
#EEC2 - Электронный контроллер двигателя 2 (Electronic Engine Controller 2)
#PGN: 0xF003
#Период: 50 мс
#Длина: 8 байт
#ID: 0x0CF00300
#EEC3 - Электронный контроллер двигателя 3 (Electronic Engine Controller 3)
#PGN: 0xFEDF
#Период: 250 мс
#Длина: 8 байт
#ID: 0x18FEDF00
#EC1 - Контроллер двигателя 1 (Engine Controller 1)
#PGN: 0xFEE3
#Период: 5000 мс
#Длина: 28 байт или 39 байт
#ID: 0x18FEE300
#HOURS - Часы работы (Hours of Operation)
#PGN: 0xFEE5
#Период: On request
#Длина: 8 байт
#ID: 0x18FEE500
#EFL/P1 - Уровень/Давление топлива двигателя 1 (Engine Fuel Level/Pressure 1)
#PGN: 0xFEEF
#Период: 500 мс
#Длина: 8 байт
#ID: 0x18FEEF00
#RC - Контроллер замедлителя (Retarder Controller)
#PGN: 0xFEE1
#Период: 5000 мс
#Длина: 19 байт
#ID: 0x18FEE100
#ET1 - Температура двигателя 1 (Engine Temperature 1)
#PGN: 0xFEEE
#Период: 1000 мс
#Длина: 8 байт
#ID: 0x18FEEE00
#ERC1 - Контроллер выхлопного тормоза 1 (Exhaust Retarder Controller 1)
#PGN: 0xF000
#Период: 100 мс
#Длина: 8 байт
#ID: 0x18F0000F
#FD - Информация о неисправностях (Fault Data)
#PGN: 0xFEBD
#Период: 1000 мс
#лина: 8 байт
#ID: 0x18FEBD00
#LFE1 - Экономия топлива 1 (Fuel Economy 1)
#PGN: 0xFEF2
#Период: 100 мс
#Длина: 8 байт
#ID: 0x18FEF200
#IC1 - Температура впускного коллектора 1 (Inlet/Manifold Temperature 1)
#PGN: 0xFEF6
#Период: 500 мс
#Длина: 8 байт
#ID: 0x18FEF600
#LFC - Расход топлива (Fuel Consumption)
#PGN: 0xFEE9
#Период: On request
#Длина: 8 байт
#ID: 0x18FEE900
#SHUTDN - Отключение (Shutdown)
#PGN: 0xFEE4
#Период: 1000 мс
#Длина: 8 байт
#ID: 0x18FEE400
#VEP1 - Электропитание автомобиля 1 (Vehicle Electrical Power 1)
#PGN: 0xFEF7
#Период: 1000 мс
#Длина: 8 байт
#ID: 0x18FEF700
#TP.CM_BAM (Engine) - Управление соединением транспортного протокола сообщение рассылаемого объявления (двигатель)
#PGN: 0xEC00
#Период: On request
#Длина: 8 байт
#ID: 0x18ECFF00
#TP.DT (Engine) - Сообщение передачи данных транспортного протокола (двигатель)
#PGN: 0xEB00
#Период: On request
#Длина: 8 байт
#ID: 0x18EBFF00
#TP.CM_BAM (Retarder) - Управление соединением транспортного протокола сообщение рассылаемого объявления (замедлитель)
#PGN: 0xEC00
#Период: On request
#Длина: 8 байт
#ID: 0x18ECFF0F
#TP.DT (Retarder) - Сообщение передачи данных транспортного протокола (замедлитель)
#PGN: 0xEB00
#Период: On request
#Длина: 8 байт
#ID: 0x18EBFF00
#Yuchai_S1 - Пользовательское сообщение, связанное с системой ECU Yuchai

#esphome run em.yaml
#https://esphome.io/components/canbus/
esphome:
  name: can_emulator
  platform: ESP32
  board: esp32dev

# Отключаем WiFi (оставлено закомментированным, для работы без WiFi просто уберите или оставьте закомментированным)
# wifi:
#   ssid: "Your_SSID"
#   password: "Your_PASSWORD"
logger:

spi:
  - id: McpSpi
    clk_pin: GPIO18
    mosi_pin: GPIO23
    miso_pin: GPIO19

canbus:
  - platform: mcp2515
    cs_pin: GPIO5
    can_id: 4
    bit_rate: 250kbps

# эмулятор CAN-сообщений
interval:
  - interval: 1000ms  # Интервал отправки сообщений
    then:
      - canbus.send:
          can_id: 0x18FEEE00 # ID температура двигателя стр.57
          use_extended_id: true
          data: [0x7D, 0x6E, 0x00, 0x2E, 0x00, 0x00, 0x00, 0x00]  # Сообщение данных
#Пример отправки пакета с температурой двигателя согласно стр.57
#Температура охлаждающей жидкости двигателя (Байт №1):
#Значение: 85°C
#Преобразование: (85 - (-40) = 125)
#Значение в канальном байте: 125 или 0x7D

#Температура топлива двигателя (Байт №2):
#Значение: 70°C
#Преобразование: (70 - (-40) = 110)
#Значение в канальном байте: 110 или 0x6E

#Температура масла двигателя (Байты №3 и №4):
#Значение: 95°C
#Преобразование с учетом точности: ((95 - (-273)) / 0.03125)
#(368 / 0.03125 = 11776)
#Значение в канальных байтах (16-битное значение): 11776 или 0x2E00
#Младший байт: 0x00
#Старший байт: 0x2E
